### ISSUE TITLE
Playground have error

### ISSUE THREAD

**Issue by Nick390** [yeonjuan/html-eslint#140]
I have try to use the playground but I get error.

**Used on**:
Google chrome 115.0.5790.171 64 bit.

 **Console**:
```
framework-22108eb722d84e59.js:9 TypeError: Cannot read properties of undefined (reading 'chunkSize')
    at eJ (9c0540d4.650e220ac4bf9bac.js:1:12916)
    at ti (9c0540d4.650e220ac4bf9bac.js:1:14406)
    at ik.markText (9c0540d4.650e220ac4bf9bac.js:1:105644)
    at os.markText (9c0540d4.650e220ac4bf9bac.js:1:169801)
    at playground-a2a51aad01c76dc2.js:1:1099
    at Array.map (<anonymous>)
    at playground-a2a51aad01c76dc2.js:1:1025
    at uU (framework-22108eb722d84e59.js:9:84130)
    at oV (framework-22108eb722d84e59.js:9:113201)
    at o (framework-22108eb722d84e59.js:9:107748)
a7 @ framework-22108eb722d84e59.js:9
main-140245b5185c1982.js:1 TypeError: Cannot read properties of undefined (reading 'chunkSize')
    at eJ (9c0540d4.650e220ac4bf9bac.js:1:12916)
    at ti (9c0540d4.650e220ac4bf9bac.js:1:14406)
    at ik.markText (9c0540d4.650e220ac4bf9bac.js:1:105644)
    at os.markText (9c0540d4.650e220ac4bf9bac.js:1:169801)
    at playground-a2a51aad01c76dc2.js:1:1099
    at Array.map (<anonymous>)
    at playground-a2a51aad01c76dc2.js:1:1025
    at uU (framework-22108eb722d84e59.js:9:84130)
    at oV (framework-22108eb722d84e59.js:9:113201)
    at o (framework-22108eb722d84e59.js:9:107748)
$ @ main-140245b5185c1982.js:1
main-140245b5185c1982.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
$ @ main-140245b5185c1982.js:1
/html-eslint/_next/data/wvQou3dCaqBcGAapc0l8u/docs/rules/undefined.json?paths=rules&paths=undefined:1     Failed to load resource: the server responded with a status of 404 ()
```

**Comment by yeonjuan** [comment]
@Nick390 Thanks for the report! I'll fix it as soon.

**Comment by yeonjuan** [comment]
@Nick390 It's fixed! https://yeonjuan.github.io/html-eslint/playground/
